# -*- coding: utf-8 -*-
"""E-commerce cleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WrZiBE1i3iI5P3Cqam8YJfHfY1xx6gin
"""

# ==============================
# 1. Import Libraries
# ==============================
import pandas as pd
import numpy as np

# ==============================
# 2. Load Dataset
# ==============================
df = pd.read_csv("/content/E-commerce final table.csv", encoding='ISO-8859-1')

# Preview data
print("Initial Shape:", df.shape)
print(df.head())

# ==============================
# 3. Standardize Column Names
# ==============================
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

print("Columns:", df.columns)

# ==============================
# 4. Check for Missing Values
# ==============================
missing = df.isnull().sum()
print("\nMissing Values:\n", missing)

# OPTIONAL: Drop rows with critical missing values
df = df.dropna(subset=['customerid', 'description'])

# ==============================
# 5. Handle Duplicates
# ==============================
duplicates = df.duplicated().sum()
print("\nDuplicate Rows:", duplicates)

df = df.drop_duplicates()

# ==============================
# 6. Fix Data Types
# ==============================
df['invoicedate'] = pd.to_datetime(df['invoicedate'])

# Clean 'unitprice_cleaned' by removing '$' and ',' before converting to numeric
df['unitprice_cleaned'] = df['unitprice_cleaned'].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False)
df['unitprice_cleaned'] = pd.to_numeric(df['unitprice_cleaned'], errors='coerce')

# Convert 'totalrevenue_cleaned' by removing '$' and ',' and converting to numeric
df['totalrevenue_cleaned'] = df['totalrevenue_cleaned'].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False)
df['totalrevenue_cleaned'] = pd.to_numeric(df['totalrevenue_cleaned'], errors='coerce')

# Convert 'quantity' to numeric
df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce')

# ==============================
# 7. Create Revenue Column (IMPORTANT)
# ==============================
df['total_revenue'] = df['quantity'] * df['unitprice_cleaned']

# ==============================
# 8. Remove Invalid Transactions
# ==============================

# Remove negative or zero values
df = df[(df['quantity'] > 0) & (df['unitprice_cleaned'] > 0)]

# ==============================
# 9. Check for Outliers
# ==============================
print("\nSummary Stats:\n", df.describe())

# OPTIONAL: Remove extreme outliers (example)
df = df[df['quantity'] < df['quantity'].quantile(0.99)]

# ==============================
# 10. Validate Revenue Calculation
# ==============================
invalid_revenue = df[
    abs(df['total_revenue'] - (df['quantity'] * df['unitprice_cleaned'])) > 0.01
]

print("\nInvalid Revenue Rows:", len(invalid_revenue))

# ==============================
# 11. Feature Engineering (Helpful for Tableau)
# ==============================
df['year'] = df['invoicedate'].dt.year
df['month'] = df['invoicedate'].dt.month
df['day'] = df['invoicedate'].dt.day

# ==============================
# 12. Final Check
# ==============================
print("\nFinal Shape:", df.shape)
print(df.info())

# ==============================
# 13. Export Clean Data
# ==============================
df.to_csv("ecommerce_clean.csv", index=False)
import os

print(os.getcwd())

print("\n✅ Data cleaning complete. File saved as 'ecommerce_clean.csv'")

# ==============================
# CORE KPIs
# ==============================

total_revenue = df['total_revenue'].sum()

total_orders = df['invoiceno'].nunique()

total_customers = df['customerid'].nunique()

total_quantity = df['quantity'].sum()

avg_order_value = total_revenue / total_orders

revenue_per_customer = total_revenue / total_customers

print("Total Revenue:", round(total_revenue, 2))
print("Total Orders:", total_orders)
print("Total Customers:", total_customers)
print("Total Quantity Sold:", total_quantity)
print("Average Order Value (AOV):", round(avg_order_value, 2))
print("Revenue per Customer:", round(revenue_per_customer, 2))

# Revenue per order
order_summary = df.groupby('invoiceno').agg({
    'total_revenue': 'sum',
    'quantity': 'sum',
    'customerid': 'first'
}).reset_index()

print(order_summary.describe())

country_metrics = df.groupby('country').agg({
    'total_revenue': 'sum',
    'invoiceno': 'nunique',
    'customerid': 'nunique'
}).rename(columns={
    'invoiceno': 'total_orders',
    'customerid': 'total_customers'
}).reset_index()

# Add calculated metrics
country_metrics['aov'] = country_metrics['total_revenue'] / country_metrics['total_orders']
country_metrics['revenue_per_customer'] = country_metrics['total_revenue'] / country_metrics['total_customers']

print(country_metrics.sort_values(by='total_revenue', ascending=False).head(10))

monthly_trends = df.groupby(['year', 'month']).agg({
    'total_revenue': 'sum',
    'invoiceno': 'nunique'
}).rename(columns={'invoiceno': 'total_orders'}).reset_index()

print(monthly_trends)

customer_orders = df.groupby('customerid')['invoiceno'].nunique()

repeat_customers = customer_orders[customer_orders > 1].count()
one_time_customers = customer_orders[customer_orders == 1].count()

print("Repeat Customers:", repeat_customers)
print("One-time Customers:", one_time_customers)
print("Repeat Rate:", repeat_customers / total_customers)

calculated_revenue = (df['quantity'] * df['unitprice_cleaned']).sum()

print("Revenue Difference:", total_revenue - calculated_revenue)

duplicate_orders = df[df.duplicated(subset=['invoiceno', 'stockcode_cleaned'], keep=False)]

print("Duplicate Order Rows:", len(duplicate_orders))

invalid_rows = df[(df['quantity'] <= 0) | (df['unitprice_cleaned'] <= 0)]

print("Invalid Rows Remaining:", len(invalid_rows))

kpi_summary = pd.DataFrame({
    "Metric": [
        "Total Revenue",
        "Total Orders",
        "Total Customers",
        "Total Quantity",
        "Average Order Value",
        "Revenue per Customer"
    ],
    "Value": [
        total_revenue,
        total_orders,
        total_customers,
        total_quantity,
        avg_order_value,
        revenue_per_customer
    ]
})

print(kpi_summary)